export const FETCH_BOOKS = 'FETCH_BOOKS';
export const FETCH_BOOK_INFO = 'FETCH_BOOK_INFO';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const MESSAGE = 'MESSAGE';